# Generated by Django 4.2.2 on 2023-06-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='file',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
    ]
